//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YerbaterosEntitys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Asiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Asiento()
        {
            this.tb_DetalleVentaPasaje = new HashSet<tb_DetalleVentaPasaje>();
        }
    
        public int Cod_Asiento { get; set; }
        public string Alias_Asiento { get; set; }
        public Nullable<int> Cod_Bus { get; set; }
        public Nullable<int> Cod_Tipo_Asiento { get; set; }
    
        public virtual tb_Bus tb_Bus { get; set; }
        public virtual tb_TipoAsiento tb_TipoAsiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DetalleVentaPasaje> tb_DetalleVentaPasaje { get; set; }
    }
}
