//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YerbaterosEntitys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Cliente()
        {
            this.tb_DetalleVentaPasaje = new HashSet<tb_DetalleVentaPasaje>();
        }
    
        public int CodNro_Cliente { get; set; }
        public Nullable<int> Cod_TipoDoc { get; set; }
        public string Nombres_Cliente { get; set; }
        public string Apellidos_Cliente { get; set; }
        public Nullable<int> Cod_Usuario { get; set; }
    
        public virtual tb_TipoDoc tb_TipoDoc { get; set; }
        public virtual tb_Usuario tb_Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DetalleVentaPasaje> tb_DetalleVentaPasaje { get; set; }
    }
}
