//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YerbaterosEntitys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DetalleVentaPasaje
    {
        public int Id_Venta { get; set; }
        public Nullable<int> Cod_Viaje { get; set; }
        public Nullable<int> CodNro_Cliente { get; set; }
        public Nullable<int> Cod_Asiento { get; set; }
        public string Voucher { get; set; }
        public Nullable<double> Costo_Ticket { get; set; }
        public Nullable<double> Descuento { get; set; }
        public Nullable<decimal> Sub_total { get; set; }
    
        public virtual tb_Asiento tb_Asiento { get; set; }
        public virtual tb_Cliente tb_Cliente { get; set; }
        public virtual tb_VentaPasaje tb_VentaPasaje { get; set; }
        public virtual tb_Viaje tb_Viaje { get; set; }
    }
}
