//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YerbaterosEntitys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Ruta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Ruta()
        {
            this.tb_Viaje = new HashSet<tb_Viaje>();
        }
    
        public int Cod_Ruta { get; set; }
        public string Alias_Ruta { get; set; }
        public Nullable<long> Tiempo_Promedio_Ruta { get; set; }
        public Nullable<int> Cod_Terminal_Origen { get; set; }
        public Nullable<int> Cod_Terminal_Destino { get; set; }
        public Nullable<double> DistanciaKm { get; set; }
    
        public virtual tb_TerminalTerrestre tb_TerminalTerrestre { get; set; }
        public virtual tb_TerminalTerrestre tb_TerminalTerrestre1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Viaje> tb_Viaje { get; set; }
    }
}
