//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YerbaterosEntitys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_TipoAsiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_TipoAsiento()
        {
            this.tb_Asiento = new HashSet<tb_Asiento>();
        }
    
        public int Cod_Tipo_Asiento { get; set; }
        public string Tipo_ASiento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Asiento> tb_Asiento { get; set; }
    }
}
