//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YerbaterosEntitys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_TerminalTerrestre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_TerminalTerrestre()
        {
            this.tb_Ruta = new HashSet<tb_Ruta>();
            this.tb_Ruta1 = new HashSet<tb_Ruta>();
        }
    
        public int Cod_Terminal { get; set; }
        public string Nombre_Terminal { get; set; }
        public Nullable<int> Cod_Departamento { get; set; }
    
        public virtual tb_Departamento tb_Departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Ruta> tb_Ruta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Ruta> tb_Ruta1 { get; set; }
    }
}
