//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YerbaterosEntitys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_VentaPasaje
    {
        public int Id { get; set; }
        public Nullable<int> Cod_Usuario { get; set; }
        public Nullable<System.DateTime> Fecha_Venta { get; set; }
        public Nullable<decimal> Monto_Total { get; set; }
    
        public virtual tb_Usuario tb_Usuario { get; set; }
        public virtual tb_DetalleVentaPasaje tb_DetalleVentaPasaje { get; set; }
    }
}
